"""Redraw documented results only; no inferred curves or new model evaluations."""
from pathlib import Path
import json
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'figures'
OUT.mkdir(exist_ok=True)
DATA = {
    'elf': {
        'source': 'elf_l_grant_summary.md, matched epoch-12 comparison (2026-09-12)',
        'synchronous_accuracy_percent': 54.1698,
        'asynchronous_accuracy_percent': 61.9409,
        'ode_steps': 32, 'distinct_test_questions': 1319,
        'generation_trials': 2638, 'inference_seeds': [42, 123],
        'same_checkpoint': True, 'ema': 0.9999,
    },
    'schedule': {
        'source': 'Learning When to Denoise, arXiv:2606.19662v1, abstract and Section 4.3',
        'url': 'https://arxiv.org/html/2606.19662v1',
        'lwd_epochs': 200, 'sfd_xl_epochs': 800,
        'autoguidance_fid_both': 1.05, 'denoiser_parameters_millions': 675,
    },
    'sharing': {
        'source': 'experiment1.pdf, page 6, matched-budget architecture table',
        'baseline': {'name': 'DiT F1024', 'parameters': 10215472, 'fid_50k': 17.574},
        'shared': {'name': 'Shared DiT-MLP H14/d32/W256', 'parameters': 10239536, 'fid_50k': 14.304},
        'dataset': 'CelebA64', 'training_seeds': 1, 'checkpoint_epoch': 400,
        'sampler_steps': 50,
    },
}
(OUT / 'feasibility_data.json').write_text(json.dumps(DATA, indent=2) + '\n')

plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 11,
                     'svg.fonttype': 'none', 'axes.spines.top': False,
                     'axes.spines.right': False, 'axes.labelcolor': '#203747',
                     'text.color': '#203747', 'xtick.color': '#405666',
                     'ytick.color': '#405666'})
fig, axes = plt.subplots(1, 3, figsize=(10.8, 4.6))
fig.subplots_adjust(left=.067, right=.983, top=.68, bottom=.26, wspace=.5)
fig.text(.025, .95, 'Existing results support the three ingredients', fontsize=17, weight='bold')
fig.text(.025, .89, 'Documented measurements; no new experiments', fontsize=11, color='#566a79')
titles = ['A. Generated Qwen states', 'B. Learned schedules', 'C. Shared prediction']
subs = ['Contextual language states generated by ELF', 'Same FID 1.05 with AutoGuidance', 'CelebA64; about 10.2M parameters']
vals = [[54.1698, 61.9409], [800, 200], [17.574, 14.304]]
ticks = [['Synchronous', 'Asynchronous'], ['SFD-XL', 'LWD'], ['DiT', 'Shared DiT-MLP']]
ylabs = ['GSM8K accuracy (%)', 'Training epochs', 'FID-50k (lower is better)']
ylims = [(0, 75), (0, 1000), (0, 22)]
notes = ['Same checkpoint; 32 ODE steps\nTwo inference seeds, same 1,319 questions',
         'Matched 675M-parameter backbone\nEpoch count, not a wall-clock estimate',
         '10.215M / 10.240M parameters\nOne training seed; epoch-400 EMA']
for k, ax in enumerate(axes):
    pos = ax.get_position()
    fig.text(pos.x0, .795, titles[k], fontsize=12, weight='bold')
    fig.text(pos.x0, .75, subs[k], fontsize=9.1, color='#566a79')
    bars = ax.bar([0, 1], vals[k], width=.58, color=['#7497bd', '#168a88'])
    ax.set_xticks([0, 1], ticks[k], fontsize=10)
    ax.set_ylim(*ylims[k])
    ax.set_ylabel(ylabs[k], fontsize=11)
    ax.yaxis.grid(True, color='#e6ebef')
    ax.set_axisbelow(True)
    for bar, value in zip(bars, vals[k]):
        label = f'{value:.2f}' if k == 0 else (f'{value:.0f}' if k == 1 else f'{value:.3f}')
        ax.text(bar.get_x()+bar.get_width()/2, value+ylims[k][1]*.025,
                label, ha='center', va='bottom', fontsize=12, weight='bold')
    fig.text(pos.x0+(pos.width/2), .135, notes[k], ha='center', va='center',
             fontsize=9.3, linespacing=1.5, color='#566a79')
fig.text(.025, .035, 'Sources: ELF-L summary; Learning When to Denoise; Experiment 1 report. Detailed qualifications are in the caption.',
         fontsize=9, color='#566a79')
for ext in ('png', 'svg'):
    fig.savefig(OUT / f'fig4_existing_feasibility.{ext}', dpi=220, facecolor='white')
plt.close(fig)
